[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "write-tui"
classifiers = ["Private :: Do Not Upload"]
version = "23.0"
dependencies = ["textual", "peewee", "tree-sitter"]

[project.optional-dependencies]
dev = ["black", "ruff", "mypy", "textual-dev"]


